name: align
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pytorch-cuda=11.7
  - intel-openmp
  - mkl=2023.1.0
  - pip
  - pip:
      - -r requirements.txt
